name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Set the tag based on git tag
      if: github.ref_type == 'tag'
      run: |        
        echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
    - name: Set the tag based on PR
      if: github.ref_type == 'branch'
      run: |        
        echo "IMAGE_TAG=${{ inputs.tag }}" >> $GITHUB_ENV    
        
    - name: Build the Docker image
      working-directory: ./consumer/container
      run: | 
        docker build . --file Dockerfile --tag jsfrnc/webhook-relay-receiver:${{ env.IMAGE_TAG }}
      
    - name: Docker Push
      run: docker push jsfrnc/webhook-relay-receiver:${{ env.IMAGE_TAG }}
