name: Docker Image CI

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  push:
    tags:
      - v1.**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Set the tag based on git tag
      if: github.ref_type == 'tag'
      run: |        
        echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "::set-output name=label::${GITHUB_REF#refs/tags/}"          
        
    - name: Set the tag based on PR
      if: github.ref_type == 'branch'
      run: |        
        echo "IMAGE_TAG=latest" >> $GITHUB_ENV    
        
    - name: Build the Docker image (webhook-relay-receiver)
      working-directory: ./receiver/container
      run: | 
        docker build . --file Dockerfile --tag jsfrnc/webhook-relay-receiver:${{ env.IMAGE_TAG }}
        
    - name: Build the Docker image (webhook-relay-consumer)
      working-directory: ./consumer/container
      run: | 
        docker build . --file Dockerfile --tag jsfrnc/webhook-relay-consumer:${{ env.IMAGE_TAG }}        
      
    - name: Docker Push
      run: | 
        docker push jsfrnc/webhook-relay-receiver:${{ env.IMAGE_TAG }}
        docker push jsfrnc/webhook-relay-consumer:${{ env.IMAGE_TAG }}
